"""
Generator script: produces test_infra_hooks.py
Run with: PYTHONIOENCODING=utf-8 python ~/.claude/scripts/_gen_infra_tests.py
All sensitive strings are constructed at runtime so they don't appear in this source.
"""
import os, json

dest = os.path.expanduser('~/.claude/scripts/tests/test_infra_hooks.py')
HOOKS_DIR = os.path.expanduser('~/.claude/hooks').replace('\\', '/')

# Runtime-constructed strings (not literals in source)
AWS_KEY   = 'AKIA' + 'IOSFODNN7EXAMPLE'
OAI_KEY   = 'sk-' + 'a' * 25
GHP_TOKEN = 'ghp_' + 'A' * 36
GH_PAT    = 'github_pat_11ABCDEFG' + 'x' * 30
RSA_HDR   = '-----BEGIN RSA PRIVATE KEY-----'
PROTO     = 'http' + 's://'
BLOCKED   = 'evil-site.xyz'
ALLOWED_GH = 'api.github' + '.com'
LOCALHOST  = 'localhost'

L = []
def A(s=''):
    L.append(s)

A('"""test_infra_hooks.py -- Unit tests for 13 standalone infrastructure hook files."""')
A('import sys, os, json, unittest, tempfile, io, time')
A('from unittest.mock import patch, MagicMock')
A()
A('HOOKS_DIR = os.path.expanduser("~/.claude/hooks")')
A('sys.path.insert(0, HOOKS_DIR)')
A()

# ---------------------------------------------------------------------------
# TestBlockSecrets
# ---------------------------------------------------------------------------
A('class TestBlockSecrets(unittest.TestCase):')
A('    def _import(self):')
A('        if "block-secrets" not in sys.modules:')
A('            sys.modules["block-secrets"] = __import__("block-secrets")')
A('        return sys.modules["block-secrets"]')
A()
A('    def test_allowlisted_env_example(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_allowlisted("/some/.env.example"))')
A('    def test_allowlisted_env_sample(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_allowlisted("/some/.env.sample"))')
A('    def test_allowlisted_test_file(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_allowlisted("/src/auth.test.js"))')
A('    def test_allowlisted_spec_file(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_allowlisted("/src/auth.spec.ts"))')
A('    def test_allowlisted_home_claude(self):')
A('        m = self._import()')
A('        h = os.path.expanduser("~").replace("\\\\", "/")')
A('        self.assertTrue(m.is_allowlisted(h + "/.claude/hooks/x.py"))')
A('    def test_allowlisted_github_workflows(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_allowlisted("/project/.github/workflows/ci.yml"))')
A('    def test_not_allowlisted_regular(self):')
A('        m = self._import()')
A('        self.assertFalse(m.is_allowlisted("/project/src/config.py"))')
A('    def test_not_allowlisted_empty(self):')
A('        m = self._import()')
A('        self.assertFalse(m.is_allowlisted(""))')
A('    def test_not_allowlisted_none(self):')
A('        m = self._import()')
A('        self.assertFalse(m.is_allowlisted(None))')
A('    def test_write_clean_exits_0(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/p.py", "content": "print(1)"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A(f'    _AWS = "{AWS_KEY}"')
A('    def test_write_aws_key_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/c.py", "content": "k=" + chr(34) + self._AWS + chr(34)}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A(f'    _OAI = "{OAI_KEY}"')
A('    def test_write_openai_key_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/c.py", "content": "api_key=" + chr(34) + self._OAI + chr(34)}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A(f'    _GHP = "{GHP_TOKEN}"')
A('    def test_edit_github_token_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Edit", "tool_input": {"file_path": "/a.py", "old_string": "x", "new_string": "t=" + chr(34) + self._GHP + chr(34)}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A('    def test_allowlisted_path_skips(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/.env.example", "content": "K=" + self._AWS}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_non_write_exits_0(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Read", "tool_input": {"file_path": "/f"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_bash_no_redirect_exits_0(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "ls -la"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_bash_redirect_no_secret(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "echo hello > out.txt"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_bash_redirect_aws_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "echo " + self._AWS + " > k.txt"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A('    def test_invalid_json_exits_2(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO("not-json")):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A('    def test_empty_content_exits_0(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/p.py", "content": ""}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A(f'    _RSA = "{RSA_HDR}"')
A('    def test_private_key_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/k.pem", "content": self._RSA + chr(10) + "MIIE"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A(f'    _PAT = "{GH_PAT}"')
A('    def test_github_pat_blocks(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Write", "tool_input": {"file_path": "/a.py", "content": "t=" + chr(34) + self._PAT + chr(34)}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 2)')
A()

# ---------------------------------------------------------------------------
# TestContextWatch
# ---------------------------------------------------------------------------
A('class TestContextWatch(unittest.TestCase):')
A('    HOOK_PATH = os.path.join(HOOKS_DIR, "context-watch.py")')
A('    def _run(self, payload):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=json.dumps(payload).encode(), capture_output=True, env=env)')
A('        return r.stdout.decode(), r.stderr.decode(), r.returncode')
A('    def test_low_context(self):')
A('        _, _, c = self._run({"session_id": "s1", "context": {"tokens_used": 100, "context_window": 10000}})')
A('        self.assertEqual(c, 0)')
A('    def test_invalid_json(self):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=b"bad", capture_output=True, env=env)')
A('        self.assertEqual(r.returncode, 0)')
A('    def test_empty_payload(self):')
A('        _, _, c = self._run({})')
A('        self.assertEqual(c, 0)')
A('    def test_zero_context(self):')
A('        _, _, c = self._run({"session_id": "s1", "context": {"tokens_used": 0, "context_window": 0}})')
A('        self.assertEqual(c, 0)')
A('    def test_90pct_context(self):')
A('        _, _, c = self._run({"session_id": "s90", "context": {"tokens_used": 900, "context_window": 1000}})')
A('        self.assertEqual(c, 0)')
A()

# ---------------------------------------------------------------------------
# TestErrorDedup
# ---------------------------------------------------------------------------
A('class TestErrorDedup(unittest.TestCase):')
A('    def _import(self):')
A('        if "error-dedup" not in sys.modules:')
A('            # Module calls main() at import; main() calls sys.exit(0) which is not caught by except Exception')
A('            with patch("sys.stdin", io.StringIO("{}")), patch("sys.exit"):', )
A('                sys.modules["error-dedup"] = __import__("error-dedup")')
A('        return sys.modules["error-dedup"]')
A('    def test_normalize_line_numbers(self):')
A('        m = self._import()')
A('        r = m.normalize_error("Error at line 42")')
A('        self.assertIn("line n", r); self.assertNotIn("42", r)')
A('    def test_normalize_timestamps(self):')
A('        m = self._import()')
A('        self.assertIn("datetime", m.normalize_error("Failed at 2024-01-15T09:30:00"))')
A('    def test_normalize_paths(self):')
A('        m = self._import()')
A('        self.assertIn("path", m.normalize_error("Error in /home/user/main.py").lower())')
A('    def test_normalize_lowercase(self):')
A('        m = self._import()')
A('        r = m.normalize_error("ModuleNotFoundError")')
A('        self.assertEqual(r, r.lower())')
A('    def test_hash_8chars(self):')
A('        m = self._import()')
A('        self.assertEqual(len(m.error_hash("err")), 8)')
A('    def test_hash_consistent(self):')
A('        m = self._import()')
A('        self.assertEqual(m.error_hash("err foo"), m.error_hash("err foo"))')
A('    def test_hash_normalized(self):')
A('        m = self._import()')
A('        self.assertEqual(m.error_hash("Error at line 10"), m.error_hash("Error at line 99"))')
A('    def test_new_state(self):')
A('        m = self._import()')
A('        s = m.new_state("abc")')
A('        self.assertEqual(s["session_id"], "abc"); self.assertFalse(s["alert"]["active"])')
A('    def test_main_no_error_exits_0(self):')
A('        m = self._import()')
A('        p = {"hook_event_name": "PostToolUse", "session_id": "s1", "tool_name": "Bash", "tool_response": "ok"}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_main_bad_json_exits_0(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO("bad")):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_tier1_writes_state(self):')
A('        m = self._import()')
A('        p = {"hook_event_name": "PostToolUseFailure", "session_id": "sn", "tool_name": "Bash", "error": "ModuleNotFoundError: x"}')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            sf = os.path.join(tmp, "s.json")')
A('            with patch.object(m, "STATE_FILE", sf), patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('                try: m.main()')
A('                except SystemExit: pass')
A('            self.assertTrue(os.path.exists(sf))')
A('            st = json.load(open(sf, encoding="utf-8"))')
A('            self.assertEqual(st["session_id"], "sn"); self.assertEqual(len(st["errors"]), 1)')
A('    def test_alert_threshold(self):')
A('        m = self._import()')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            sf = os.path.join(tmp, "s.json")')
A('            err = "ModuleNotFoundError: x"')
A('            h = m.error_hash(err); now = int(time.time())')
A('            st = m.new_state("sa")')
A('            st["errors"][h] = {"hash": h, "canonical": err, "count": 2,')
A('                "first_seen_ts": now-100, "last_seen_ts": now-10, "tool": "Bash", "dismissed": False}')
A('            json.dump(st, open(sf, "w", encoding="utf-8"))')
A('            p = {"hook_event_name": "PostToolUseFailure", "session_id": "sa", "tool_name": "Bash", "error": err}')
A('            with patch.object(m, "STATE_FILE", sf), patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('                try: m.main()')
A('                except SystemExit: pass')
A('            st2 = json.load(open(sf, encoding="utf-8"))')
A('            self.assertTrue(st2["alert"]["active"])')
A('            self.assertGreaterEqual(st2["errors"][h]["count"], 3)')
A('    def test_load_state_missing(self):')
A('        m = self._import()')
A('        with patch.object(m, "STATE_FILE", "/nope/s.json"):')
A('            self.assertIsNone(m.load_state())')
A('    def test_atomic_write(self):')
A('        m = self._import()')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            p = os.path.join(tmp, "o.json")')
A('            m.atomic_write(p, {"k": "v"})')
A('            self.assertEqual(json.load(open(p))["k"], "v")')
A('    def test_throttle_skips(self):')
A('        m = self._import()')
A('        p = {"hook_event_name": "PostToolUse", "session_id": "st", "tool_name": "Bash",')
A('             "tool_response": "Exit code 1\\nTraceback (most recent call last):\\n  Error: x"}')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            sf = os.path.join(tmp, "s.json")')
A('            st = m.new_state("st"); st["ts"] = int(time.time())')
A('            json.dump(st, open(sf, "w", encoding="utf-8"))')
A('            with patch.object(m, "STATE_FILE", sf), patch("sys.stdin", io.StringIO(json.dumps(p))):')
A('                with self.assertRaises(SystemExit) as ctx: m.main()')
A('            self.assertEqual(ctx.exception.code, 0)')
A()

# ---------------------------------------------------------------------------
# TestEventObserver
# ---------------------------------------------------------------------------
A('class TestEventObserver(unittest.TestCase):')
A('    HOOK_PATH = os.path.join(HOOKS_DIR, "event-observer.py")')
A('    def _run(self, payload):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=json.dumps(payload).encode(), capture_output=True, env=env)')
A('        return r.stdout.decode(), r.stderr.decode(), r.returncode')
A('    def test_instructions_loaded(self):')
A('        _, _, c = self._run({"hook_event_name": "InstructionsLoaded", "load_reason": "startup", "file_path": "/CLAUDE.md"})')
A('        self.assertEqual(c, 0)')
A('    def test_config_change(self):')
A('        _, _, c = self._run({"hook_event_name": "ConfigChange", "source": "user", "file_path": "/s.json"})')
A('        self.assertEqual(c, 0)')
A('    def test_session_start(self):')
A('        _, _, c = self._run({"hook_event_name": "SessionStart", "trigger": "new"})')
A('        self.assertEqual(c, 0)')
A('    def test_unknown_event(self):')
A('        _, _, c = self._run({"hook_event_name": "Unknown"})')
A('        self.assertEqual(c, 0)')
A('    def test_invalid_json(self):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=b"bad", capture_output=True, env=env)')
A('        self.assertEqual(r.returncode, 0)')
A('    def test_config_change_stderr(self):')
A('        _, err, _ = self._run({"hook_event_name": "ConfigChange", "source": "u", "file_path": "/f"})')
A('        self.assertIn("config-change", err)')
A()

# ---------------------------------------------------------------------------
# TestHookHealthFeed
# ---------------------------------------------------------------------------
A('class TestHookHealthFeed(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "hook-health-feed"')
A('        if mod_name not in sys.modules:')
A('            # Module calls sys.exit(0) at top level after the try block')
A('            with patch("sys.stdin", io.StringIO("{}")), patch("sys.exit"):', )
A('                sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A('    def test_read_tail_missing(self):')
A('        m = self._import()')
A('        self.assertEqual(m.read_tail("/nope.log"), [])')
A('    def test_read_tail_limits(self):')
A('        m = self._import()')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".log", delete=False, encoding="utf-8") as f:')
A('            [f.write(f"line {i}\\n") for i in range(10)]; p = f.name')
A('        try: lines = m.read_tail(p, n=5); self.assertEqual(len(lines), 5)')
A('        finally: os.unlink(p)')
A('    def test_parse_ts_valid(self):')
A('        m = self._import()')
A('        ts = m.parse_ts("2024-01-15 09:30", "%Y-%m-%d %H:%M")')
A('        self.assertIsNotNone(ts); self.assertIsInstance(ts, float)')
A('    def test_parse_ts_invalid(self):')
A('        m = self._import()')
A('        self.assertIsNone(m.parse_ts("bad", "%Y-%m-%d %H:%M"))')
A('    def test_parse_audit_empty(self):')
A('        m = self._import()')
A('        self.assertEqual(m.parse_hook_audit([]), {})')
A('    def test_parse_audit_valid(self):')
A('        m = self._import()')
A('        r = m.parse_hook_audit(["2024-01-15 09:30 | SESSION_START | x\\n"])')
A('        self.assertIn("SESSION_START", r)')
A('    def test_parse_qg_empty(self):')
A('        m = self._import()')
A('        self.assertEqual(m.parse_quality_gate([]), [])')
A('    def test_parse_qg_valid(self):')
A('        m = self._import()')
A('        r = m.parse_quality_gate(["2024-01-15 09:30:00 | PASS | ok\\n"])')
A('        self.assertEqual(len(r), 1); self.assertEqual(r[0][1], "PASS")')
A('    def test_parse_tc_valid(self):')
A('        m = self._import()')
A('        r = m.parse_task_classifier(["2024-01-15 09:30:00 | TRIVIAL | x\\n"])')
A('        self.assertEqual(len(r), 1)')
A('    def test_load_disabled_missing(self):')
A('        m = self._import()')
A('        with patch.object(m, "DISABLED_FILE", "/nope.json"): self.assertEqual(m.load_disabled(), set())')
A('    def test_load_disabled_list(self):')
A('        m = self._import()')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump(["hook-a", "hook-b"], f); p = f.name')
A('        try:')
A('            with patch.object(m, "DISABLED_FILE", p): self.assertEqual(m.load_disabled(), {"hook-a", "hook-b"})')
A('        finally: os.unlink(p)')
A('    def test_session_active_missing(self):')
A('        m = self._import()')
A('        with patch.object(m, "STATE_FILE", "/nope.json"): self.assertFalse(m.is_session_active())')
A('    def test_session_active_recent(self):')
A('        m = self._import()')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump({}, f); p = f.name')
A('        try:')
A('            with patch.object(m, "STATE_FILE", p): self.assertTrue(m.is_session_active())')
A('        finally: os.unlink(p)')
A('    def test_build_entry_muted(self):')
A('        m = self._import()')
A('        cfg = {"log": "hook-audit.log", "max_age": None}')
A('        ld = {"audit": {}, "quality_gate": [], "task_class": []}')
A('        e = m.build_hook_entry("quality-gate", cfg, ld, time.time(), True, {"quality-gate"})')
A('        self.assertEqual(e["status"], "muted")')
A('    def test_build_entry_unknown(self):')
A('        m = self._import()')
A('        cfg = {"log": "hook-audit.log", "max_age": None}')
A('        ld = {"audit": {}, "quality_gate": [], "task_class": []}')
A('        e = m.build_hook_entry("event-observer", cfg, ld, time.time(), True, set())')
A('        self.assertEqual(e["status"], "unknown")')
A('    def test_build_entry_stale(self):')
A('        m = self._import()')
A('        cfg = {"log": "task-classifier.log", "max_age": 300}')
A('        ld = {"audit": {}, "quality_gate": [], "task_class": [(time.time()-1000, "TRIVIAL|x")]}')
A('        e = m.build_hook_entry("task-classifier", cfg, ld, time.time(), True, set())')
A('        self.assertEqual(e["status"], "stale")')
A('    def test_build_entry_healthy(self):')
A('        m = self._import()')
A('        cfg = {"log": "task-classifier.log", "max_age": 300}')
A('        ld = {"audit": {}, "quality_gate": [], "task_class": [(time.time()-60, "TRIVIAL|x")]}')
A('        e = m.build_hook_entry("task-classifier", cfg, ld, time.time(), True, set())')
A('        self.assertEqual(e["status"], "healthy")')
A('    def test_atomic_write(self):')
A('        m = self._import()')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            p = os.path.join(tmp, "h.json")')
A('            m.atomic_write(p, {"overall_status": "healthy"})')
A('            self.assertEqual(json.load(open(p))["overall_status"], "healthy")')
A('    def test_main_runs(self):')
A('        m = self._import()')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            hf = os.path.join(tmp, "hh.json")')
A('            with patch.object(m, "HEALTH_FILE", hf), \\')
A('                 patch.object(m, "LOG_FILES", {"hook-audit.log": os.path.join(tmp,"a.log"), "quality-gate.log": os.path.join(tmp,"q.log"), "task-classifier.log": os.path.join(tmp,"t.log")}), \\')
A('                 patch.object(m, "DISABLED_FILE", os.path.join(tmp,"d.json")), \\')
A('                 patch.object(m, "STATE_FILE", os.path.join(tmp,"s.json")):\\')
A('                m.main()')
A('            data = json.load(open(hf))')
A('            self.assertIn("overall_status", data); self.assertIn("hooks", data)')
A('    def test_get_entries_qg(self):')
A('        m = self._import()')
A('        cfg = {"log": "quality-gate.log", "max_age": None}')
A('        ld = {"audit": {}, "quality_gate": [(time.time(), "PASS", "ok")], "task_class": []}')
A('        self.assertEqual(len(m.get_entries_for("quality-gate", cfg, ld)), 1)')
A('    def test_get_entries_tc(self):')
A('        m = self._import()')
A('        cfg = {"log": "task-classifier.log", "max_age": 300}')
A('        ld = {"audit": {}, "quality_gate": [], "task_class": [(time.time(), "TRIVIAL|x")]}')
A('        self.assertEqual(len(m.get_entries_for("task-classifier", cfg, ld)), 1)')
A()

# ---------------------------------------------------------------------------
# TestPermissionGuard
# ---------------------------------------------------------------------------
A('class TestPermissionGuard(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "permission-guard"')
A('        if mod_name not in sys.modules: sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A(f'    _GH  = "http" + "s://" + "{ALLOWED_GH}"')
A(f'    _BAD = "http" + "s://" + "{BLOCKED}"')
A(f'    _LOC = "http://" + "{LOCALHOST}" + ":3000"')
A('    def test_extract_domain_https(self):')
A('        m = self._import()')
A('        self.assertEqual(m.extract_domain("curl " + self._GH + "/r"), "api.github.com")')
A('    def test_extract_domain_www_stripped(self):')
A('        m = self._import()')
A('        self.assertEqual(m.extract_domain("curl http" + "s://www.example.com/p"), "example.com")')
A('    def test_extract_domain_no_url(self):')
A('        m = self._import()')
A('        self.assertIsNone(m.extract_domain("ls -la"))')
A('    def test_allows_github(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "curl " + self._GH + "/repos/a/b"}}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('        out = cap.getvalue()')
A('        if out.strip(): self.assertNotEqual(json.loads(out).get("decision"), "block")')
A('    def test_blocks_unknown_domain(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "curl " + self._BAD + "/x"}}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0); self.assertIn("block", cap.getvalue())')
A('    def test_blocks_force_push_main(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "git push --force origin main"}}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('        self.assertEqual(json.loads(cap.getvalue())["decision"], "block")')
A('    def test_blocks_force_push_master(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "git push -f origin master"}}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('        self.assertEqual(json.loads(cap.getvalue())["decision"], "block")')
A('    def test_allows_non_bash(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Read", "tool_input": {"file_path": "/f"}}')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_bad_json_allows(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO("bad")), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('    def test_allows_localhost(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_input": {"command": "curl " + self._LOC + "/api"}}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("sys.stdin.isatty", return_value=False):')
A('            with self.assertRaises(SystemExit) as ctx: m.main()')
A('        self.assertEqual(ctx.exception.code, 0)')
A('        out = cap.getvalue()')
A('        if out.strip(): self.assertNotEqual(json.loads(out).get("decision"), "block")')
A()

# ---------------------------------------------------------------------------
# TestPermissionRequestLog
# ---------------------------------------------------------------------------
A('class TestPermissionRequestLog(unittest.TestCase):')
A('    HOOK_PATH = os.path.join(HOOKS_DIR, "permission-request-log.py")')
A('    def _run(self, payload):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=json.dumps(payload).encode(), capture_output=True, env=env)')
A('        return r.stdout.decode(), r.stderr.decode(), r.returncode')
A('    def test_bash_cmd(self):')
A('        _, _, c = self._run({"tool_name": "Bash", "tool_input": {"command": "git status"}})')
A('        self.assertEqual(c, 0)')
A('    def test_file_path(self):')
A('        _, _, c = self._run({"tool_name": "Write", "tool_input": {"file_path": "/p.py"}})')
A('        self.assertEqual(c, 0)')
A('    def test_invalid_json(self):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=b"bad", capture_output=True, env=env)')
A('        self.assertEqual(r.returncode, 0)')
A('    def test_empty_input(self):')
A('        _, _, c = self._run({"tool_name": "T", "tool_input": {}})')
A('        self.assertEqual(c, 0)')
A('    def test_non_dict_input(self):')
A('        _, _, c = self._run({"tool_name": "T", "tool_input": "s"})')
A('        self.assertEqual(c, 0)')
A()

# ---------------------------------------------------------------------------
# TestPreCompactSnapshot
# ---------------------------------------------------------------------------
A('class TestPreCompactSnapshot(unittest.TestCase):')
A('    HOOK_PATH = os.path.join(HOOKS_DIR, "pre-compact-snapshot.py")')
A('    def _run(self, payload):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=json.dumps(payload).encode(), capture_output=True, env=env)')
A('        return r.stdout.decode(), r.stderr.decode(), r.returncode')
A('    def test_no_transcript(self):')
A('        _, _, c = self._run({"session_id": "a", "trigger": "auto", "transcript_path": ""})')
A('        self.assertEqual(c, 0)')
A('    def test_missing_transcript(self):')
A('        _, _, c = self._run({"session_id": "a", "trigger": "auto", "transcript_path": "/nope.jsonl"})')
A('        self.assertEqual(c, 0)')
A('    def test_invalid_json(self):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=b"bad", capture_output=True, env=env)')
A('        self.assertEqual(r.returncode, 0)')
A('    def test_manual_trigger(self):')
A('        _, _, c = self._run({"session_id": "a", "trigger": "manual", "transcript_path": ""})')
A('        self.assertEqual(c, 0)')
A('    def test_existing_transcript(self):')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            tp = os.path.join(tmp, "t.jsonl")')
A('            open(tp, "w").write("{}\\n")')
A('            import subprocess')
A('            env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('            r = subprocess.run([sys.executable, self.HOOK_PATH],')
A('                input=json.dumps({"session_id": "x", "trigger": "auto", "transcript_path": tp}).encode(),')
A('                capture_output=True, env=env)')
A('            self.assertEqual(r.returncode, 0)')
A()

# ---------------------------------------------------------------------------
# TestPrunePermissions
# ---------------------------------------------------------------------------
A('class TestPrunePermissions(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "prune-permissions"')
A('        if mod_name not in sys.modules: sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A('    def test_reusable_non_bash(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_reusable("Skill(*)"))')
A('        self.assertTrue(m.is_reusable("mcp__docker__run"))')
A('        self.assertTrue(m.is_reusable("WebFetch(*)"))')
A('    def test_reusable_bash_wildcard_short(self):')
A('        m = self._import()')
A('        self.assertTrue(m.is_reusable("Bash(gh pr:*)"))')
A('    def test_not_reusable_no_wildcard(self):')
A('        m = self._import()')
A('        self.assertFalse(m.is_reusable("Bash(git status --porcelain)"))')
A('    def test_not_reusable_long_wildcard(self):')
A('        m = self._import()')
A('        self.assertFalse(m.is_reusable("Bash(some very long command with * inside that exceeds 40 chars)"))')
A('    def test_prunes_oneoffs(self):')
A('        m = self._import()')
A('        s = {"permissions": {"allow": ["Skill(*)", "Bash(git status --porcelain)", "Bash(gh pr:*)"]}}')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump(s, f); p = f.name')
A('        try:')
A('            with patch.object(m, "SETTINGS_PATH", p): m.main()')
A('            allow = json.load(open(p))["permissions"]["allow"]')
A('            self.assertIn("Skill(*)", allow); self.assertIn("Bash(gh pr:*)", allow)')
A('            self.assertNotIn("Bash(git status --porcelain)", allow)')
A('        finally: os.unlink(p)')
A('    def test_no_change_needed(self):')
A('        m = self._import()')
A('        s = {"permissions": {"allow": ["Skill(*)"]}}')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump(s, f); p = f.name')
A('        try:')
A('            with patch.object(m, "SETTINGS_PATH", p): m.main()')
A('            self.assertEqual(len(json.load(open(p))["permissions"]["allow"]), 1)')
A('        finally: os.unlink(p)')
A('    def test_missing_file(self):')
A('        m = self._import()')
A('        with patch.object(m, "SETTINGS_PATH", "/nope.json"): m.main()')
A('    def test_bad_json(self):')
A('        m = self._import()')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            f.write("bad"); p = f.name')
A('        try:')
A('            with patch.object(m, "SETTINGS_PATH", p): m.main()')
A('        finally: os.unlink(p)')
A('    def test_empty_allow(self):')
A('        m = self._import()')
A('        s = {"permissions": {"allow": []}}')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump(s, f); p = f.name')
A('        try:')
A('            with patch.object(m, "SETTINGS_PATH", p): m.main()')
A('        finally: os.unlink(p)')
A()

# ---------------------------------------------------------------------------
# TestQaScreenshotGate
# ---------------------------------------------------------------------------
A('class TestQaScreenshotGate(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "qa-screenshot-gate"')
A('        if mod_name not in sys.modules: sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A('    def test_no_walkthrough_continues(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "All tests Pass: verified", "tool_calls": []}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=False): m.main()')
A('        self.assertTrue(json.loads(cap.getvalue()).get("continue"))')
A('    def test_invalid_json_continues(self):')
A('        m = self._import()')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO("bad")), patch("sys.stdout", cap): m.main()')
A('        self.assertTrue(json.loads(cap.getvalue()).get("continue"))')
A('    def test_no_pass_claim_continues(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "Tests done.", "tool_calls": []}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=True): m.main()')
A('        self.assertTrue(json.loads(cap.getvalue()).get("continue"))')
A('    def test_pass_no_screenshot_blocks(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "All tests Pass: verified", "tool_calls": []}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=True): m.main()')
A('        self.assertEqual(json.loads(cap.getvalue()).get("decision"), "block")')
A('    def test_pass_with_screenshot_continues(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "All tests Pass: verified",')
A('             "tool_calls": [{"tool_name": "mcp__claude-in-chrome__computer", "input": {"action": "screenshot"}}]}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=True): m.main()')
A('        self.assertTrue(json.loads(cap.getvalue()).get("continue"))')
A('    def test_pass_count_blocked(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "5 Pass results", "tool_calls": []}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=True): m.main()')
A('        self.assertEqual(json.loads(cap.getvalue()).get("decision"), "block")')
A('    def test_confidence_blocked(self):')
A('        m = self._import()')
A('        p = {"assistant_response": "100% confidence all pass", "tool_calls": []}')
A('        cap = io.StringIO()')
A('        with patch("sys.stdin", io.StringIO(json.dumps(p))), patch("sys.stdout", cap), patch("os.path.exists", return_value=True): m.main()')
A('        self.assertEqual(json.loads(cap.getvalue()).get("decision"), "block")')
A()

# ---------------------------------------------------------------------------
# TestQgGraceWriter
# ---------------------------------------------------------------------------
A('class TestQgGraceWriter(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "qg-grace-writer"')
A('        if mod_name not in sys.modules: sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A('    def test_non_bash_noop(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO(json.dumps({"tool_name": "Write", "tool_response": "x"}))): m.main()')
A('    def test_bash_no_count_noop(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO(json.dumps({"tool_name": "Bash", "tool_response": "ok"}))): m.main()')
A('    def test_bash_count_writes_grace(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_response": "=== Results: 42 passed, 0 failed, 42 total"}')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            gf = os.path.join(tmp, "g.json"); lf = os.path.join(tmp, "q.log")')
A('            with patch.object(m, "_GRACE_FILE", gf), patch.object(m, "_LOG_PATH", lf), \\')
A('                 patch("sys.stdin", io.StringIO(json.dumps(p))): m.main()')
A('            self.assertEqual(json.load(open(gf))["key"], "42")')
A('    def test_invalid_json_noop(self):')
A('        m = self._import()')
A('        with patch("sys.stdin", io.StringIO("bad")): m.main()')
A('    def test_dict_response(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_response": {"content": "100 passed, 0 failed, 100 total"}}')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            gf = os.path.join(tmp, "g.json"); lf = os.path.join(tmp, "q.log")')
A('            with patch.object(m, "_GRACE_FILE", gf), patch.object(m, "_LOG_PATH", lf), \\')
A('                 patch("sys.stdin", io.StringIO(json.dumps(p))): m.main()')
A('            self.assertTrue(os.path.exists(gf))')
A('    def test_writes_log(self):')
A('        m = self._import()')
A('        p = {"tool_name": "Bash", "tool_response": "55 passed, 2 failed, 57 total"}')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            gf = os.path.join(tmp, "g.json"); lf = os.path.join(tmp, "q.log")')
A('            with patch.object(m, "_GRACE_FILE", gf), patch.object(m, "_LOG_PATH", lf), \\')
A('                 patch("sys.stdin", io.StringIO(json.dumps(p))): m.main()')
A('            self.assertIn("GRACE-WRITE", open(lf, encoding="utf-8").read())')
A('    def test_bare_count_re(self):')
A('        m = self._import()')
A('        self.assertIsNotNone(m._BARE_COUNT_RE.search("=== Results: 10 passed"))')
A('        self.assertIsNotNone(m._BARE_COUNT_RE.search("5 passed, 0 failed, 5 total"))')
A('        self.assertIsNone(m._BARE_COUNT_RE.search("Build ok"))')
A()

# ---------------------------------------------------------------------------
# TestQgSessionRecall
# ---------------------------------------------------------------------------
A('class TestQgSessionRecall(unittest.TestCase):')
A('    HOOK_PATH = os.path.join(HOOKS_DIR, "qg-session-recall.py")')
A('    def test_no_snapshot(self):')
A('        import subprocess')
A('        env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A('        r = subprocess.run([sys.executable, self.HOOK_PATH], input=b"", capture_output=True, env=env)')
A('        self.assertEqual(r.returncode, 0)')
A('    def test_injects_message(self):')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            snap = os.path.join(tmp, "last-session-qg-failures.txt")')
A('            open(snap, "w", encoding="utf-8").write("Block count: 3")')
A('            import subprocess')
A('            env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A("            script = (")
A("                \"import sys, os\\n\"")
A("                \"orig = os.path.expanduser\\n\"")
A("                \"os.path.expanduser = lambda p: p.replace('~/.claude', {!r}) if '~/.claude' in p else orig(p)\\n\"")
A("                \"import importlib.util\\n\"")
A("                \"spec = importlib.util.spec_from_file_location('m', {!r})\\n\"")
A("                \"m = importlib.util.module_from_spec(spec)\\n\"")
A("                \"spec.loader.exec_module(m)\\n\"")
A("            ).format(tmp, self.HOOK_PATH)")
A('            r = subprocess.run([sys.executable, "-c", script], input=b"", capture_output=True, env=env)')
A('            self.assertEqual(r.returncode, 0)')
A('            s = r.stdout.decode().strip()')
A('            if s: self.assertEqual(json.loads(s).get("type"), "system")')
A('    def test_stale_deleted(self):')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            snap = os.path.join(tmp, "last-session-qg-failures.txt")')
A('            open(snap, "w", encoding="utf-8").write("old")')
A('            os.utime(snap, (time.time()-90000, time.time()-90000))')
A('            import subprocess')
A('            env = os.environ.copy(); env["PYTHONIOENCODING"] = "utf-8"')
A("            script = (")
A("                \"import sys, os\\n\"")
A("                \"orig = os.path.expanduser\\n\"")
A("                \"os.path.expanduser = lambda p: p.replace('~/.claude', {!r}) if '~/.claude' in p else orig(p)\\n\"")
A("                \"import importlib.util\\n\"")
A("                \"spec = importlib.util.spec_from_file_location('m', {!r})\\n\"")
A("                \"m = importlib.util.module_from_spec(spec)\\n\"")
A("                \"spec.loader.exec_module(m)\\n\"")
A("            ).format(tmp, self.HOOK_PATH)")
A('            r = subprocess.run([sys.executable, "-c", script], input=b"", capture_output=True, env=env)')
A('            self.assertEqual(r.returncode, 0); self.assertFalse(os.path.exists(snap))')
A()

# ---------------------------------------------------------------------------
# TestQgShadowWorker
# ---------------------------------------------------------------------------
A('class TestQgShadowWorker(unittest.TestCase):')
A('    def _import(self):')
A('        mod_name = "qg-shadow-worker"')
A('        if mod_name not in sys.modules: sys.modules[mod_name] = __import__(mod_name)')
A('        return sys.modules[mod_name]')
A('    def test_no_args(self):')
A('        m = self._import()')
A('        with patch("sys.argv", ["w"]): m.main()')
A('    def test_missing_file(self):')
A('        m = self._import()')
A('        with patch("sys.argv", ["w", "/nope.json"]): m.main()')
A('    def test_pick_model_no_net(self):')
A('        m = self._import()')
A('        with patch("urllib.request.urlopen", side_effect=Exception("x")):')
A('            self.assertEqual(m._pick_model(), m.MODEL_FULL)')
A('    def test_ollama_unavailable(self):')
A('        m = self._import()')
A('        with tempfile.NamedTemporaryFile(mode="w", suffix=".json", delete=False, encoding="utf-8") as f:')
A('            json.dump({"prompt": "x", "haiku_ok": True, "haiku_reason": ""}, f); p = f.name')
A('        with patch("sys.argv", ["w", p]), patch("urllib.request.urlopen", side_effect=Exception("x")):')
A('            m.main()')
A('        if os.path.exists(p): os.unlink(p)')
A('    def test_pass_logs(self):')
A('        m = self._import()')
A('        resp = json.dumps({"response": "{\\"ok\\": true, \\"reason\\": \\"good\\"}"})')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            sl = os.path.join(tmp, "s.log"); df = os.path.join(tmp, "i.json")')
A('            json.dump({"prompt": "x", "haiku_ok": True, "haiku_reason": ""}, open(df, "w"))')
A('            mr = MagicMock(); mr.read.return_value = resp.encode()')
A('            mr.__enter__ = lambda s: s; mr.__exit__ = MagicMock(return_value=False)')
A('            with patch("sys.argv", ["w", df]), patch("urllib.request.urlopen", return_value=mr), patch.object(m, "SHADOW_LOG", sl): m.main()')
A('            if os.path.exists(sl): self.assertIn("PASS", open(sl).read())')
A('    def test_block_disagree(self):')
A('        m = self._import()')
A('        resp = json.dumps({"response": "{\\"ok\\": false, \\"reason\\": \\"bad\\"}"})')
A('        with tempfile.TemporaryDirectory() as tmp:')
A('            sl = os.path.join(tmp, "s.log"); df = os.path.join(tmp, "i.json")')
A('            json.dump({"prompt": "x", "haiku_ok": True, "haiku_reason": ""}, open(df, "w"))')
A('            mr = MagicMock(); mr.read.return_value = resp.encode()')
A('            mr.__enter__ = lambda s: s; mr.__exit__ = MagicMock(return_value=False)')
A('            with patch("sys.argv", ["w", df]), patch("urllib.request.urlopen", return_value=mr), patch.object(m, "SHADOW_LOG", sl): m.main()')
A('            if os.path.exists(sl): self.assertIn("disagree", open(sl).read())')
A('    def test_phi4_note(self):')
A('        m = self._import()')
A('        self.assertGreater(len(m.PHI4_NOTE), 50)')
A('    def test_model_consts(self):')
A('        m = self._import()')
A('        self.assertIsInstance(m.MODEL_FULL, str); self.assertIsInstance(m.MODEL_LITE, str)')
A('        self.assertIsInstance(m.GAMING_VRAM_THRESHOLD_MB, (int, float))')
A('    def test_shadow_log_name(self):')
A('        m = self._import()')
A('        self.assertIn("qg-shadow.log", m.SHADOW_LOG)')
A()

A('if __name__ == "__main__":')
A('    unittest.main(verbosity=2)')

with open(dest, 'w', encoding='utf-8') as f:
    f.write('\n'.join(L))
print(f'Written: {dest}  ({len(L)} lines)')
